/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;


import Process.UpdateTable;
import javax.swing.JOptionPane;
import Process.*;
import java.sql.ResultSet;



/**
 *
 * @author MyPC
 */
public class QLNS_Phongban extends javax.swing.JFrame {
    public static String sql="SELECT * FROM qlns.phongban order by name";
    public static String id;// biến tạm lưu cho việc sửa và xóa

    /**
     * Creates new form QLNS_Phongban
     */
    public QLNS_Phongban() {
        initComponents();
        // gọi hàm đổ dữ liệu ra table
        ShowBG();
        ProcessCrt(false);
        this.btAdd.setEnabled(true);
    }
    public void ProcessCrt(boolean b)
    {
        this.btAdd.setEnabled(b);
        this.btDelete.setEnabled(b);
        this.btEdit.setEnabled(b);
    }
    public void ShowBG()
    {
        UpdateTable.LoadData(sql, tbPhongBan);
        this.lbTong.setText("Số bản ghi :"+this.tbPhongBan.getRowCount()+"");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel_header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Idphongban = new javax.swing.JLabel();
        jLabel_tenphong = new javax.swing.JLabel();
        jLabel_DiaChi = new javax.swing.JLabel();
        jLabel_sodienthoai = new javax.swing.JLabel();
        txtMaPB = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        btNew = new javax.swing.JButton();
        txtSerch = new javax.swing.JTextField();
        btSerch = new javax.swing.JButton();
        jPanel_body = new javax.swing.JPanel();
        jLabel_Chucnang = new javax.swing.JLabel();
        btBack = new javax.swing.JButton();
        btAdd = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPhongBan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lbTong = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(193, 255, 193));

        jPanel1.setBackground(new java.awt.Color(192, 255, 193));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Thông tin phòng ban");

        jLabel_Idphongban.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Idphongban.setText("Mã phòng ban   :");

        jLabel_tenphong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_tenphong.setText("Tên phòng ban :");

        jLabel_DiaChi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_DiaChi.setText("Địa chỉ             :");

        jLabel_sodienthoai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_sodienthoai.setText("Số điện thoại    :");

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        btNew.setText("Nhập mới");
        btNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewActionPerformed(evt);
            }
        });

        txtSerch.setText("Tìm kiếm");
        txtSerch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSerchMouseClicked(evt);
            }
        });
        txtSerch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerchActionPerformed(evt);
            }
        });

        btSerch.setText("Tìm Kiếm");
        btSerch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSerchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_headerLayout = new javax.swing.GroupLayout(jPanel_header);
        jPanel_header.setLayout(jPanel_headerLayout);
        jPanel_headerLayout.setHorizontalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel_headerLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel_tenphong)
                                .addComponent(jLabel_sodienthoai, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_DiaChi, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel_Idphongban))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaPB)
                            .addComponent(txtName)
                            .addComponent(txtAddress)
                            .addComponent(txtPhone))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btNew, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_headerLayout.createSequentialGroup()
                                .addComponent(txtSerch, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(btSerch, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(32, 32, 32))
        );
        jPanel_headerLayout.setVerticalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_headerLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Idphongban)
                    .addComponent(txtMaPB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNew, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_tenphong)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_DiaChi)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSerch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSerch))
                .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_headerLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel_sodienthoai)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jPanel_headerLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtPhone)
                        .addContainerGap())))
        );

        jPanel_body.setBackground(new java.awt.Color(255, 211, 155));

        jLabel_Chucnang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_Chucnang.setText("Chức năng");

        btBack.setBackground(new java.awt.Color(255, 0, 0));
        btBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btBack.setText("Quay Lại");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        btAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btAdd.setText("Thêm");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btEdit.setBackground(new java.awt.Color(255, 102, 102));
        btEdit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEdit.setText("Sửa");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btDelete.setBackground(new java.awt.Color(255, 255, 51));
        btDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btDelete.setText("Xóa");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_bodyLayout = new javax.swing.GroupLayout(jPanel_body);
        jPanel_body.setLayout(jPanel_bodyLayout);
        jPanel_bodyLayout.setHorizontalGroup(
            jPanel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Chucnang)
                .addGap(41, 41, 41)
                .addComponent(btBack)
                .addGap(64, 64, 64)
                .addComponent(btAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(btEdit)
                .addGap(70, 70, 70)
                .addComponent(btDelete)
                .addGap(39, 39, 39))
        );
        jPanel_bodyLayout.setVerticalGroup(
            jPanel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btBack)
                        .addComponent(btAdd)
                        .addComponent(btEdit)
                        .addComponent(btDelete))
                    .addComponent(jLabel_Chucnang))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 246, 143));

        tbPhongBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã phòng ban", "Tên phòng ban", "Địa chỉ", "Số điện thoại"
            }
        ));
        tbPhongBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPhongBanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPhongBan);

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        lbTong.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbTong, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTong, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
      QLNS_Menu menu=new QLNS_Menu();
      menu.setVisible(true);
      this.dispose();
       
    }//GEN-LAST:event_btBackActionPerformed

    private void tbPhongBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPhongBanMouseClicked

        
        ProcessCrt(true);
        this.btAdd.setEnabled(false);
        
        try
        {
            // lấy ra dòng dữ liệu vừa clcik chuột và trỏ nó đến id của nó 
            int row=this.tbPhongBan.getSelectedRow();
            String IDRow=(this.tbPhongBan.getModel().getValueAt(row, 0)).toString();
            String sql1="SELECT * FROM qlns.phongban where idPhongban='"+IDRow+"'";
            // đọc dữ liệu có mã là idRow rồi ghi nó lên cách textfield và combobox
            ResultSet rs = UpdateTable.ShowData(sql1);
            if(rs.next())// nêys có dữ liệu
            {
                id=rs.getString("idPhongban");
                this.txtMaPB.setText(rs.getString("idPhongban"));
                this.txtName.setText(rs.getString("name"));
                this.txtAddress.setText(rs.getString("Address"));
                this.txtPhone.setText(rs.getString("phone"));
            }
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Thông báo lỗi");
            
        }
    }//GEN-LAST:event_tbPhongBanMouseClicked

    private void btNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewActionPerformed
        ProcessCrt(false);
        this.btAdd.setEnabled(true);
        this.txtMaPB.setText("");
        this.txtName.setText("");
        this.txtAddress.setText("");
        this.txtPhone.setText("");
        this.txtMaPB.requestFocus();
    }//GEN-LAST:event_btNewActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
       if(this.txtMaPB.getText().length()==0)
           JOptionPane.showMessageDialog(null, "Mã phòng ban không được bỏ trống","Thông Báo",1);
       else
           if(this.txtName.getText().length()==0 || this.txtAddress.getText().length()==0 || this.txtPhone.getText().length()==0 )
               JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ dữ liệu","Thông Báo",1);
       else
               if(this.txtMaPB.getText().length() >10 || this.txtPhone.getText().length() >11 )
                    JOptionPane.showMessageDialog(null, "Bạn nhập quá số kí tự Mã Phòng Ban và Phone","Thông Báo",1);
       else
               {
                  PhongBan.InsertPB(this.txtMaPB.getText().trim(), this.txtName.getText(), this.txtAddress.getText(), this.txtPhone.getText());
                  ShowBG();
                   ProcessCrt(false);
               }
    }//GEN-LAST:event_btAddActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        if(this.txtMaPB.getText().length()==0)
           JOptionPane.showMessageDialog(null, "Mã phòng ban không được bỏ trống","Thông Báo",1);
       else
           if(this.txtName.getText().length()==0 || this.txtAddress.getText().length()==0 || this.txtPhone.getText().length()==0 )
               JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ dữ liệu","Thông Báo",1);
       else
               if(this.txtMaPB.getText().length() >10 || this.txtPhone.getText().length() >11 )
                    JOptionPane.showMessageDialog(null, "Bạn nhập quá số kí tự Mã Phòng Ban và Phone","Thông Báo",1);
       else
               {
                  // lấy id ở bộ nhớ tạm ra so sánh để update lại
                   PhongBan.UpdatePB(this.txtMaPB.getText().trim(), this.txtName.getText(), this.txtAddress.getText(), this.txtPhone.getText(),id);
                  ShowBG();
                   ProcessCrt(false);
               }
    }//GEN-LAST:event_btEditActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
       if(this.txtMaPB.getText().length()==0)
           JOptionPane.showMessageDialog(null, "Không tìm thấy Mã phòng ban nào cần xóa","Thông Báo",1);
       else
       {
           if(JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa ?","Thông báo",2)==0)
           {
               PhongBan.DeletePB(id);
               ShowBG();
               ProcessCrt(false);
           }
       }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void txtSerchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerchActionPerformed
      
    }//GEN-LAST:event_txtSerchActionPerformed

    private void txtSerchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSerchMouseClicked
        this.txtSerch.setText("");
        this.txtSerch.requestFocus();
    }//GEN-LAST:event_txtSerchMouseClicked

    private void btSerchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSerchActionPerformed
       if(this.txtSerch.getText().length()==0)
           JOptionPane.showMessageDialog(null, "Vui lòng nhập từ khóa để tìm kiếm","Thông báo",1);
       else
       {
           String sql="SELECT *FROM qlns.phongban WHERE idPhongban like'%"+this.txtSerch.getText()+"%' or name like'%"+this.txtSerch.getText()+"%' or Address like'%"+this.txtSerch.getText()+"%'";
           UpdateTable.LoadData(sql, tbPhongBan);
           this.lbTong.setText("Số bản ghi tìm thấy :"+this.tbPhongBan.getRowCount()+"");
       }
    }//GEN-LAST:event_btSerchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNS_Phongban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNS_Phongban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNS_Phongban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNS_Phongban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNS_Phongban().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btBack;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btNew;
    private javax.swing.JButton btSerch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Chucnang;
    private javax.swing.JLabel jLabel_DiaChi;
    private javax.swing.JLabel jLabel_Idphongban;
    private javax.swing.JLabel jLabel_sodienthoai;
    private javax.swing.JLabel jLabel_tenphong;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_body;
    private javax.swing.JPanel jPanel_header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTong;
    private javax.swing.JTable tbPhongBan;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtMaPB;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSerch;
    // End of variables declaration//GEN-END:variables
}
