/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlynhansu;

/**
 *
 * @author MyPC
 */
public class QLNS_NhanVien extends javax.swing.JFrame {

    /**
     * Creates new form QLNS_NhanVien
     */
    public QLNS_NhanVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel_header = new javax.swing.JPanel();
        jLabel_thongtinNV = new javax.swing.JLabel();
        jLabel_manv = new javax.swing.JLabel();
        jLabel_tennv = new javax.swing.JLabel();
        jLabel_Chucvu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_gioitinh = new javax.swing.JLabel();
        jLabel_Ngaysinh = new javax.swing.JLabel();
        jLabel_Noisinh = new javax.swing.JLabel();
        jLabel_SoCMNND = new javax.swing.JLabel();
        jLabel_Sodt = new javax.swing.JLabel();
        jLabel_Dantoc = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField_tennv = new javax.swing.JTextField();
        jTextField_Noisinh = new javax.swing.JTextField();
        jTextField_Sodt = new javax.swing.JTextField();
        jTextField_Dantoc = new javax.swing.JTextField();
        jTextField_ChucVu = new javax.swing.JTextField();
        jRadioButton_nam = new javax.swing.JRadioButton();
        jRadioButton_Nu = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField_maphongban = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel_Chucnang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_Xem = new javax.swing.JButton();
        jButton_Them = new javax.swing.JButton();
        jButton_Sua = new javax.swing.JButton();
        jButton_Xóa = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_thongtinNV.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel_thongtinNV.setText("Thông tin nhân viên");

        jLabel_manv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_manv.setText("Mã nhân viên :");

        jLabel_tennv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_tennv.setText("Tên nhân viên:");

        jLabel_Chucvu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Chucvu.setText("Mã chức vụ  :");

        jLabel_gioitinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_gioitinh.setText("Giới tính          :");

        jLabel_Ngaysinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Ngaysinh.setText("Ngày sinh:");

        jLabel_Noisinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Noisinh.setText("Nơi sinh   :");

        jLabel_SoCMNND.setText("Số CMND :");

        jLabel_Sodt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Sodt.setText("Số điện thoại:");

        jLabel_Dantoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Dantoc.setText("Dân tộc   :");

        buttonGroup1.add(jRadioButton_nam);
        jRadioButton_nam.setText("Nam");

        buttonGroup1.add(jRadioButton_Nu);
        jRadioButton_Nu.setText("Nữ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Mã phòng ban:");

        jTextField_maphongban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_maphongbanActionPerformed(evt);
            }
        });

        jTextField2.setText("jTextField2");

        javax.swing.GroupLayout jPanel_headerLayout = new javax.swing.GroupLayout(jPanel_header);
        jPanel_header.setLayout(jPanel_headerLayout);
        jPanel_headerLayout.setHorizontalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_headerLayout.createSequentialGroup()
                .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_headerLayout.createSequentialGroup()
                        .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_headerLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Chucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_headerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel_gioitinh)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_Nu)
                            .addComponent(jRadioButton_nam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_headerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_headerLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_maphongban))
                            .addGroup(jPanel_headerLayout.createSequentialGroup()
                                .addComponent(jLabel_manv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1))
                            .addComponent(jLabel_thongtinNV)
                            .addGroup(jPanel_headerLayout.createSequentialGroup()
                                .addComponent(jLabel_tennv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_ChucVu)
                                    .addComponent(jTextField_tennv, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_headerLayout.createSequentialGroup()
                        .addComponent(jLabel_Dantoc)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Dantoc))
                    .addGroup(jPanel_headerLayout.createSequentialGroup()
                        .addComponent(jLabel_Ngaysinh)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2))
                    .addGroup(jPanel_headerLayout.createSequentialGroup()
                        .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Noisinh)
                            .addComponent(jLabel_SoCMNND))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Noisinh))
                    .addGroup(jPanel_headerLayout.createSequentialGroup()
                        .addComponent(jLabel_Sodt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Sodt, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                .addGap(71, 71, 71))
        );
        jPanel_headerLayout.setVerticalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_headerLayout.createSequentialGroup()
                .addComponent(jLabel_thongtinNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_manv)
                    .addComponent(jLabel_Ngaysinh)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_headerLayout.createSequentialGroup()
                        .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_headerLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Noisinh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_SoCMNND))
                            .addGroup(jPanel_headerLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jTextField_Noisinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Sodt)
                            .addComponent(jTextField_Sodt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Chucvu)))
                    .addGroup(jPanel_headerLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)))
                .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_headerLayout.createSequentialGroup()
                        .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_headerLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_Dantoc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Dantoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_headerLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextField_maphongban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jLabel_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel_headerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton_nam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_Nu)
                        .addContainerGap())))
        );

        jPanel_Chucnang.setBackground(new java.awt.Color(238, 220, 130));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setText("Chức năng");

        jButton_Xem.setBackground(new java.awt.Color(51, 255, 255));
        jButton_Xem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Xem.setText("Xem");

        jButton_Them.setBackground(new java.awt.Color(255, 204, 0));
        jButton_Them.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Them.setText("Thêm");
        jButton_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemActionPerformed(evt);
            }
        });

        jButton_Sua.setBackground(new java.awt.Color(255, 255, 0));
        jButton_Sua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Sua.setText("Sửa");

        jButton_Xóa.setBackground(new java.awt.Color(255, 255, 51));
        jButton_Xóa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Xóa.setText("Xóa");

        javax.swing.GroupLayout jPanel_ChucnangLayout = new javax.swing.GroupLayout(jPanel_Chucnang);
        jPanel_Chucnang.setLayout(jPanel_ChucnangLayout);
        jPanel_ChucnangLayout.setHorizontalGroup(
            jPanel_ChucnangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ChucnangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_ChucnangLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jButton_Xem)
                .addGap(111, 111, 111)
                .addComponent(jButton_Them)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Sua)
                .addGap(69, 69, 69)
                .addComponent(jButton_Xóa)
                .addGap(25, 25, 25))
        );
        jPanel_ChucnangLayout.setVerticalGroup(
            jPanel_ChucnangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ChucnangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ChucnangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Xem)
                    .addComponent(jButton_Them)
                    .addComponent(jButton_Sua)
                    .addComponent(jButton_Xóa))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 211, 155));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Chucnang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_Chucnang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ThemActionPerformed

    private void jTextField_maphongbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_maphongbanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_maphongbanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNS_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNS_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNS_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNS_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNS_NhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_Them;
    private javax.swing.JButton jButton_Xem;
    private javax.swing.JButton jButton_Xóa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_Chucvu;
    private javax.swing.JLabel jLabel_Dantoc;
    private javax.swing.JLabel jLabel_Ngaysinh;
    private javax.swing.JLabel jLabel_Noisinh;
    private javax.swing.JLabel jLabel_SoCMNND;
    private javax.swing.JLabel jLabel_Sodt;
    private javax.swing.JLabel jLabel_gioitinh;
    private javax.swing.JLabel jLabel_manv;
    private javax.swing.JLabel jLabel_tennv;
    private javax.swing.JLabel jLabel_thongtinNV;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_Chucnang;
    private javax.swing.JPanel jPanel_header;
    private javax.swing.JRadioButton jRadioButton_Nu;
    private javax.swing.JRadioButton jRadioButton_nam;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField_ChucVu;
    private javax.swing.JTextField jTextField_Dantoc;
    private javax.swing.JTextField jTextField_Noisinh;
    private javax.swing.JTextField jTextField_Sodt;
    private javax.swing.JTextField jTextField_maphongban;
    private javax.swing.JTextField jTextField_tennv;
    // End of variables declaration//GEN-END:variables
}
